#!/usr/bin/env bash
set -e

cd ~
echo -n "RAD repo name: "
read NAME
[ -z "$NAME" ] && echo "No name" && exit 1

DIR=~/"$NAME"
mkdir -p "$DIR"
cd "$DIR"

if [ ! -d .git ]; then
  git init
  git branch -M main
fi

echo -n "RAD input (what should this repo become?): "
read INTENT

cat <<HTML > index.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>RAD — $NAME</title>
  <style>
    body{background:#05070c;color:#e9f0ff;font-family:system-ui;margin:0;padding:24px}
    .card{max-width:900px;margin:0 auto;border:1px solid #1a2a55;border-radius:18px;padding:18px;background:rgba(10,20,40,.55)}
    .title{display:flex;align-items:center;justify-content:space-between}
    .rad{font-weight:800;letter-spacing:.12em}
    input{width:100%;padding:14px 16px;border-radius:14px;border:1px solid #264a9a;background:#071022;color:#e9f0ff;font-size:16px}
    button{margin-top:10px;padding:12px 16px;border-radius:14px;border:0;background:#1d6bff;color:white;font-weight:700}
    pre{white-space:pre-wrap;background:#060b16;border-radius:14px;padding:12px;border:1px solid #12224b}
    .small{opacity:.8;font-size:13px}
  </style>
</head>
<body>
  <div class="card">
    <div class="title">
      <div class="rad">RAD</div>
      <div class="small">$NAME</div>
    </div>
    <h2>Repo Builder Terminal</h2>
    <p class="small">Type intent → this repo becomes a module. (Next cart will connect RAD to autopilot.)</p>
    <input id="q" placeholder="Describe what to build..."/>
    <button onclick="go()">Generate Plan</button>
    <pre id="out"></pre>
  </div>
<script>
function go(){
  const q=document.getElementById('q').value.trim();
  const out=document.getElementById('out');
  out.textContent = q
    ? ("INTENT:\\n" + q + "\\n\\nNEXT:\\n- Create carts\\n- Write docs\\n- Add index pages\\n- Link to Infinity Engine\\n")
    : "Type something first.";
}
</script>
</body>
</html>
HTML

cat <<JSON > rad.json
{
  "repo": "$NAME",
  "intent": "$(printf "%s" "$INTENT" | sed 's/"/\\"/g')",
  "created_utc": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
}
JSON

cat <<MD > README.md
# $NAME

RAD intent:
> $INTENT

This repo is generated by RAD and will be wired into Infinity Autopilot.
MD

git add -A
git commit -m "RAD bootstrap: $NAME" >/dev/null 2>&1 || true

echo "[∞] RAD repo created at $DIR"
echo "[∞] Next: add remote / push when ready."
