github.com:
    users:
        pewpi-infinity:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: pewpi-infinity
